### ISSUE TITLE
Error regarding the Angles 

### ISSUE THREAD

**Issue by MunirehHosseinzada** [kkla320/GaugeProgressViewStyle#10]
Hi. I have added this package to my project. But after adding this package I got these errors and tried to use .gauge style for my progressView, I got these errors.

1- Argument type 'SwiftUI.Angle' does not conform to expected type 'Trigonometry.Angle' (CGPoint+init.swift)
2- Type 'ProgressViewStyle' has no member 'gauge' (ContentView.swift)

**Comment by kkla320** [comment]
Hi,
Can you please tell me for what platform you try to build? I will try to reproduce the bug on my system as well and try to fix is as fast as possible.

**Comment by kkla320** [comment]
I found the issue and fixed it in Version 1.0.1

**Comment by mattgreen** [comment]
I am still seeing this happen, unfortunately. Building an iOS app targeting 15.4, I have Trigonometry 1.0.1 and GaugeProgressViewStyle 1.0.1.

Looking at the fix, I'm confused as to what the intent is with this line of code: 
```
#if canImport(SwiftUI) && (!os(iOS) || arch(arm64))
```

Should the file be ignored entirely on iOS? If so, then the following `@available` line is misleading. However, the usage in the library seems to suggest that a `SwiftUI.Angle` is expected to conform to the `Trigonometry.Angle` as it is used.

**Comment by kkla320** [comment]
I`ll reopen the issue and have a look again. Thanks for pointing it out again.

**Comment by gabehoffman** [comment]
I'm getting this error as well now. I can build to `Any iOS Device (arm64)` but if I target the simulator for an iPad it breaks. This wasn't an issue a couple of weeks ago.

**Comment by kkla320** [comment]
I created a new branch with a potential fix. If you @gabehoffman and @mattgreen  could have a look, I would appreciate the help. The fix is on branch fix/#10_Angles.

**Comment by kkla320** [comment]
I merged my fix and created a new release 1.0.2. With this release you should be able to compile the project again.
